### PR TITLE
remove Autotools

### PR DESCRIPTION
**Pull request by guijan**
Build tested on Alpine Linux and OpenBSD.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I think it's ok to remove autools CI stuff and other files except configure.ac and Makefile.am

2 files are enough to keep autotools so that even ancient and extremely exotic systems can compile the lib

I think meson requires python 3.7+ (2018), autotools tarballs somehow work on systems released 15 years ago

**Comment by guijan** [comment]
I'm in the camp that thinks that if an user can download this software, they can update their OS too. And if they use some OS that has ceased development entirely like Xinuos OpenServer or something, they can just install any of the free unices. I don't intend to work on support for systems and versions that are abandoned by their own creators, the user can migrate to something actively maintained instead.

Using Meson definitely prevents this program from running on systems that are very much alive, there is no official Meson support for HP-UX, IBM AIX, QNX, and LynxOS among others. Although Meson has undocumented support for some of them, as can be seen with glib having QNX support:
https://github.com/GNOME/glib/blob/43a7435c9c54e64ad7869e356f975db501381aea/meson.build#L203-L205
To bring support to systems such as those, and if I can get access to such a system through CI or a SSH login to develop the program on it, I'd consider it. Otherwise I'm not personally interested in it, maybe the main maintainer has a different idea.

**Comment by wdlkmpx** [comment]
Sometimes it's about hardware support, it's possible to install newer distro versions, but the hardware may not be that compatible unless it's CLI only

There is muon, a small C version of meson, it doesn't need a damn recent python version... it can make it work anywhere I guess, but every time a project deletes autotools, a star dies... no other tools make cross compiling so easy

**Comment by guijan** [comment]
Is this based on a need you have or is it all theoretical?

**Comment by wdlkmpx** [comment]
I use a distro that has python 3.5 and obviously it can't run a recent meson version, my hatred of meson began, some really old machines can't really handle the latest kernel/xorg combination

Until I found muon, a C app that compiles in a few seconds and supports most mesonbuild files I tried to compile

I  cross compile static apps, and muon says it doesn't support cross compiling, but it does support cross compiling, with proper cflags and ldflags

This project: Muon and meson dont properly detect Intl when cross compiling, so I recommend removing this line

https://github.com/argp-standalone/argp-standalone/blob/master/meson.build#L52

Because this project doesn't have any translations (po Dir / po files)

You can also #define gettext(x) (x)

**Comment by guijan** [comment]
That's a nice change, send it as a PR. I can't look at it now because I'm sleepy.

What distro and hardware is that? In my experience, if you pick your software carefully, early 2000s hardware is fine, late 90s is probably doable. Unless you have one of those ARM computers that never got mainline Linux support and need to run an old patched Linux kernel to get it to work at all, just try a lighter Linux distro like Void Linux (preferrably the Musl version) or a BSD, NetBSD tends to work best on toasters. I'm really not going to be the one to commit changes to support outdated systems, the main maintainer might have a different opinion.

**Pull request merged**
