### PR TITLE
Allow both static and shared builds using Meson on non Windows platforms

### PR DESCRIPTION
**Pull request by diizzyy**
Allow builds to be both or either static and shared instead of hardcoding static and create symlinks for shared library as used in multiple distributions

### CODE REVIEW

**Comment by diizzyy** [comment]
@wolfv 
Hi, can you have a look at this?

**Comment by wolfv** [comment]
Hi @diizzyy! Thanks for the PRs :)
Could you check the windows failure?

**Comment by diizzyy** [comment]
@wolfv 
Let's give this a try

**Comment by wolfv** [comment]
Do you want a release of this?

**Comment by diizzyy** [comment]
That would be great, thanks! :-)

**Pull request merged**
