### PR TITLE
remove more autogoo

### PR DESCRIPTION
**Pull request by guijan**
I've build tested this on OpenBSD and Alpine Linux.

### CODE REVIEW

**Comment by guijan** [comment]
@wolfv 
Mentioning you to cause a notification. BTW, I'm not sure if it's intentional but you might want to click the "Watch" button at the top of the page to be notified of activity in this repository.

Could you also enable issues in the repository?

I'm here because I'm interested in trying to get this argp-standalone fork into OpenBSD in the future, their argp-standalone is 18 years old.

**Comment by wolfv** [comment]
thanks @guijan !

**Comment by wolfv** [comment]
sorry, I indeed only saw your PRs now! Are you interested in co-maintaining this?

**Comment by guijan** [comment]
Yes, I am.

**Pull request merged**
